#pragma once
#define WINDOW_CLASS_NAME L"MARIO"
#define MAIN_WINDOW_TITLE L"MARIO BROS 3"
#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 800
#define BRICK_TEXTURE_PATH L"brick.png"

#define BACKGROUND_COLOR D3DCOLOR_XRGB(255, 0, 0)