#ifndef MARIODEFINES_H
#define MARIODEFINES_H
#endif


#define WINDOW_CLASS_NAME L"MARIO"
#define MAIN_WINDOW_TITLE L"MARIO BROS 3"
#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 800
#define BRICK_TEXTURE_PATH L"brick.png"

#define BACKGROUND_COLOR D3DCOLOR_XRGB(0, 0, 0)

#define PATH_TEX_MARIO L"Textures\\mario.png"